name: pynrc

dependencies:
    - python>=3.7
    - numpy>=1.19
    - matplotlib>=3.3.0
    - scipy>=1.5.0
    - tqdm>4
    - astropy>=4.2
    - Cython
    - pip
    - pip:
        - sphinx>=3.4.1
        - sphinx-automodapi
        - ipykernel
        - nbsphinx
        - docutils==0.16
        - astroquery>=0.4.3
        - poppy>=1.0
        - webbpsf>=1.0
        - pysynphot>=2.0
        # - git+https://github.com/JarronL/webbpsf_ext.git
