name: pynrc

channels:
    - astropy

dependencies:
    - python=3.5
    - numpy>=1.13
    - matplotlib=2.0.2
    - astropy=3.1
    - astropy-helpers=3.1
    - Cython
    - sphinx-automodapi
    - sphinx>=1.5.1
    - ipykernel
    - nbsphinx
    - pip:
        -e git+https://github.com/spacetelescope/poppy.git#egg=poppy
        -e git+https://github.com/spacetelescope/webbpsf.git#egg=webbpsf
        -e git+https://github.com/spacetelescope/pysynphot.git#egg=pysynphot

